### PR TITLE
Reformatted all xml files, linted readme

### PR DESCRIPTION
**Pull request by sryu1**
This shouldn't affect the aircraft performance.

### CODE REVIEW

**Comment by sryu1** [comment]
@ijkannan All good to be merged now 👍

**Comment by sryu1** [comment]
Hey @sriemmanuel787  Could you merge this?

**Comment by naviat-dev** [comment]
I've looked at it and the changes look good, but I don't think i can merge it to #unstable-dev.
I can merge it to main, though.

**Comment by sryu1** [comment]
Oh yeah, sure, I think it was already requesting to merge to main though...
image

**Comment by sryu1** [comment]
So are you going to merge it @sriemmanuel787? I don't wanna do all this again if someone commits to this repo and my PR gets messed up...

**Pull request merged**
